""" A python script to clean problem files generated by running workflow.py
    This script can clean the files generated by the last run of the problem,
    it can clean the binaries generated from makebin.py, or it can
    clear both.  'python clear.py all' restores the workflow folder to its state
    before makebin.py or workflow.py was called, retaining only


    Usage:
        python clean.py ('run' OR 'binaries' OR 'all')
"""
import sys
import subprocess

files_from_last_run = ['out/*',
                       '*inp *log *timing',
                       'Sdesign/*position*',
                       'Sdesign/*log',
                       'Sdesign/*inp',
                       'Fdata/*',
                       'Fresults/ARW2.*',
                       'Fresults/deformed*',
                       'Fresults/deformed_ARW2.*',
                       'Fresults/Restart/*',
                       'Fresults/fluid.position*',
                       'Fresults/DEFAULT*',
                       'Sresults/*',
                       'AeroS-Files/materialfile',
                       'AeroS-Files/groupfile',
                       'tet*.xpost',
                       'fluidposition.xpost',
                       'DEFAULT*',
                       'AeroF-Files/deformed*'
                        ]

binary_files = ['binaries/*',
                'binaries/binLog/*',
                'AeroF-Files/ARW2.top.dec.*'
               ]

def clean_last_run():
    """Remove files generated by the last set of simulations."""
    for file in files_from_last_run:
        subprocess.call('rm -f '+file, shell=True)

def clean_binaries():
    """Remove binary input files."""
    for file in binary_files:
        subprocess.call('rm -f '+file, shell=True)


if __name__ == '__main__':
    if sys.argv[1] == 'run':
        clean_last_run()
    if sys.argv[1] == 'binaries':
        clean_binaries()
    if sys.argv[1] == 'all':
        clean_last_run()
        clean_binaries()